### ISSUE TITLE
URLs with atypical domains cause Encoder panics

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#148]
For some reason this causes a panic:

```
url: https://earthquake.usgs.gov
connectionStrings:
  - mongodb://mongo1:27017/eqs
rateLimit:
  burst: 5
  period: 1
requests:
  - endpoint: /fdsnws/event/1/query
    query:
      format: geojson
      starttime: 2020-01-01
      endtime: 2020-01-2
```
