### ISSUE TITLE
Add request-level truncate

### ISSUE THREAD

**Issue by prestonvasquez** [alpine-hodler/gidari#155]
A user should be able to define "truncate" on a single request in the configuration file. For example:

```yml
requests:
  - endpoint: /my/stuffs
    truncate: true
```

This should truncate the `stuffs` data before upserting the payload.
